# Generated by Django 3.2 on 2021-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInstosk',
            new_name='countInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='numRewiews',
            new_name='numReviews',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
